baseURL = "http://marissanovak.com"
languageCode = "en-us"
title = "Marissa Novak"
theme = "coder"

languagecode = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "MarissaNovak"

[params]
    author = "Marissa Novak"
    description = "Marissa Novak's personal website"
    keywords = "blog,developer,personal"
    info = "Software Developer and Model"
    # avatarurl = "images/avatar.jpg"
    # footercontent = "Enter a text here."

    hideCredits = true
    hideCopyright = true


    # Custom CSS
    custom_css = []

    # RTL support
    rtl = false

[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/mnovak12/"
[[params.social]]
    name = "Instagram"
    weight = 2
    url = "https://instagram.com/marissa.novak/"
[[params.social]]
    name = "LinkedIn"
    weight = 3
    url = "https://www.linkedin.com/in/marissa-novak-137a3b61/"
[[params.social]]
    name = "Yelp"
    weight = 4
    url = "https://www.yelp.com/user_details?userid=YKP-L8m8ROyh4DqkiRwVog"
[[params.social]]
    name = "ModelMayhem"
    weight = 5
    url = "https://www.modelmayhem.com/marissanovak/"

#[[menu.main]]
#    name = "About"
#    weight = 2
#    url = "/about/"